# Generated by Django 4.0.4 on 2022-05-06 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_remove_artist_band_alter_artist_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='albums',
        ),
        migrations.AddField(
            model_name='album',
            name='band',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalogue.band'),
        ),
        migrations.AlterField(
            model_name='album',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalogue.artist'),
        ),
    ]
