# Generated by Django 4.0.4 on 2022-05-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_remove_band_albums_album_band_alter_album_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='role',
            field=models.ManyToManyField(to='catalogue.role'),
        ),
    ]
