# Generated by Django 4.0.4 on 2022-05-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='album_pics'),
        ),
    ]
