# Generated by Django 4.0.4 on 2022-05-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_alter_album_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.ImageField(default='album_pics/default.jpg', upload_to='album_pics'),
        ),
    ]
