# Generated by Django 4.0.4 on 2022-05-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_alter_album_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='band_pics'),
        ),
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='album_pics'),
        ),
    ]
