# Generated by Django 4.0.4 on 2022-05-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0011_band_image_alter_album_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='artist_pics'),
        ),
    ]
