# Generated by Django 4.0.4 on 2022-05-31 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0012_artist_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='John', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='github',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='Doe', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
