# Generated by Django 4.0.4 on 2022-06-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0013_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.IntegerField(choices=[(1, '1 - Very Bad'), (2, '2 - Bad'), (3, '3 - Decent'), (4, '4 - Very Good'), (5, '5 - Excellent')], default=0),
        ),
    ]
